### ISSUE TITLE
Check if it is possible to correctly adjust scroll on some linking scenarios

### ISSUE THREAD

**Issue by jchoude** [nipy/dipy_web#24] opened 2016-08-19 14:19 UTC
From PR #17 :

However, if I go to, for example: http://dipy.herokuapp.com/tutorials/ and then click on Contextual Enhancement, it unfolds. Then, if I click on "Crossing-preserving contextual enhancement", I am taken to http://dipy.herokuapp.com/documentation/0.12.0.dev/examples_built/contextual_enhancement/#example-contextual-enhancement , where the adjustement doesn't work. Not a huge issue, as I said previously.

**Comment by ghoshbishakh** [comment] 2016-08-19 16:16
@jchoude I am really struggling on that point. I am trying a lot of things but nothing seems to work properly. The problem is if I scroll the page to proper offset on document load even then after the page loads completely it goes back to the original anchor. And delaying the offset adjustment too much is giving an unexpected jump, that is the page has loaded and suddenly it snaps a bit up. Lot of people on stackoverflow have reported that 1ms delay is working for them. But may be things have changed with the browsers now.

**Comment by jchoude** [comment] 2016-08-19 17:42
Ok, that's what I suspected. That's why my issue is called: "Check if it is possible...". We shouldn't put a huge focus on this.

**Comment by ghoshbishakh** [comment] 2016-08-19 17:45
@jchoude lets keep it open for a while.

**Comment by skoudoro** [comment] 2019-08-19 18:18
closing, we can not reproduce, Feel free to reopen it if needed.

**Closed by skoudoro** 2019-08-19 18:18 UTC
